version: "3"
services:

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432" # use port that you want to in your local instead of 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile"
    environment:
      - PORT=3000
    volumes:
      - .:/myapp
      - rails_log:/myapp/log
    ports:
      - "3000:3000" # use port that you want to in your local instead of 3091
    depends_on:
      - db

volumes:
  db:
  rails_log: